version: "3.9"

volumes:
  koiwai-pgdata:
  asagi:
  s3:

services:
  mokou:
    build: .
    deploy:
      replicas: 1

  asagi:
    environment:
      - MYSQL_ROOT_PASSWORD=123
    image: mysql:5.6
    volumes:
      - asagi:/var/lib/mysql

  koiwai:
    environment:
      - POSTGRES_PASSWORD=koiwai
      - POSTGRES_USER=koiwai
      - POSTGRES_DB=koiwai
      - PGDATA=/var/lib/postgresql/data/14.3
    image: postgres:14.3-alpine
    volumes:
      - koiwai-pgdata:/var/lib/postgresql/data
      - /koiwai-tablespace:/koiwai-tablespace

  s3:
    command: "server /data --console-address \":9001\""
    environment:
      - MINIO_ROOT_USER=koiwai
      - MINIO_ROOT_PASSWORD=12345678
    image: quay.io/minio/minio
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - s3:/data
